version: "3.7"
services:
  nginx:
    image: openresty/openresty:alpine
    ports:
      - "80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./log/nginx/:/data/log/nginx/:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.08'
              memory: 512M