version: "3.7"
services:
  nginx1:
    image: openresty/openresty:alpine
    ports:
      - "8081:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 0
              memory: 512M

  nginx2:
    image: openresty/openresty:alpine
    ports:
      - "8082:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 1
              memory: 512M

  nginx3:
    image: openresty/openresty:alpine
    ports:
      - "8083:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 2
              memory: 512M

  nginx4:
    image: openresty/openresty:alpine
    ports:
      - "8084:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 3
              memory: 512M

  nginx5:
    image: openresty/openresty:alpine
    ports:
      - "8085:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 4
              memory: 512M

  nginx6:
    image: openresty/openresty:alpine
    ports:
      - "8086:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 5
              memory: 512M

  nginx7:
    image: openresty/openresty:alpine
    ports:
      - "8087:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 6
              memory: 512M

  nginx8:
    image: openresty/openresty:alpine
    ports:
      - "8088:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.8'
              cpuset: 7
              memory: 512M              