version: "3.4"

services:
  apisix1:
    build:
      context: ./
      dockerfile: centos/Dockerfile1
    restart: always
    volumes:
      - ./apisix_conf/config1.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 512M
    network_mode: host


  apisix2:
    build:
      context: ./
      dockerfile: centos/Dockerfile2
    restart: always
    volumes:
      - ./apisix_conf/config2.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 512M
    network_mode: host


  apisix3:
    build:
      context: ./
      dockerfile: centos/Dockerfile3
    restart: always
    volumes:
      - ./apisix_conf/config3.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: 512M
    network_mode: host


  etcd:
    # if you are in the mainland China, please use Azure China mirror:
    # image: gcr.azk8s.cn/etcd-development/etcd:v3.3.12
    image: gcr.io/etcd-development/etcd:v3.3.12
    command: /usr/local/bin/etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
    ports:
      - "2379:2379"
    networks:
      - net-etcd

  web1:
    image: openresty/openresty:alpine
    ports:
      - "8001:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M

  web2:
    image: openresty/openresty:alpine
    ports:
      - "8002:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web3:
    image: openresty/openresty:alpine
    ports:
      - "8003:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web4:
    image: openresty/openresty:alpine
    ports:
      - "8004:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web5:
    image: openresty/openresty:alpine
    ports:
      - "8005:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web6:
    image: openresty/openresty:alpine
    ports:
      - "8006:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web7:
    image: openresty/openresty:alpine
    ports:
      - "8007:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web8:
    image: openresty/openresty:alpine
    ports:
      - "8008:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web9:
    image: openresty/openresty:alpine
    ports:
      - "8009:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M


  web10:
    image: openresty/openresty:alpine
    ports:
      - "8010:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./www/:/data/data/www/:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 512M    

networks:
  net-etcd:
