apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  rules:
  - host: testhost
    http:
      paths:
      - path: /test
        backend:
          serviceName: http-svc
          servicePort: 80
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 80