apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-ingress
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: http-svc
          servicePort: 80
      - path: /
        backend:
          serviceName: http-svc
          servicePort: 80          